Repository pagopa/pagopa-ecommerce-user-stats-service, pull requests merged in 2024-10, with the labels that each got.

#2 feat: [CHK-3289] CI CD pipeline + helm chart files
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/gradle-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  gradle/verification-metadata.xml
  helm/.helmignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/large, patch, chart-patch

#3 CHK-3297 api spec implementation
  api-spec/v1/user-stats-api.yaml
  build.gradle.kts
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageController.kt
  src/main/kotlin/it/pagopa/ecommerce/users/exceptions/ApiError.kt
  src/main/kotlin/it/pagopa/ecommerce/users/exceptions/UserNotFoundException.kt
  src/main/kotlin/it/pagopa/ecommerce/users/exceptions/handlers/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/exceptions/handlers/ExceptionHandlerTest.kt
Labels: size/large, patch, chart-patch

#6 fix: docker build
  Dockerfile
Labels: patch, chart-patch, size/small

#5 [CHK-3296] feat: add mongo configuration for user-stats with mock
  .env.example
  .env.local
  README.md
  docker-compose.yml
  docker/config/mongo/mongo-init.js
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/users/documents/LastUsage.kt
  src/main/kotlin/it/pagopa/ecommerce/users/documents/UserStatistics.kt
  src/main/kotlin/it/pagopa/ecommerce/users/repositories/UserStatisticsRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/users/UserTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/users/documents/UserStatisticsTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/services/UsersStatisticsServiceTest.kt
  src/test/resources/application.test.properties
Labels: patch, chart-patch, size/small

#7 feat: add logic to persist user preferences
  build.gradle.kts
  docker-compose.yml
  gradle.lockfile
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/ecommerce/users/config/mongo/MongoConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/users/config/mongo/converters/OffsetDateTimeConverters.kt
  src/main/kotlin/it/pagopa/ecommerce/users/config/mongo/converters/UUIDConverters.kt
  src/main/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageController.kt
  src/main/kotlin/it/pagopa/ecommerce/users/documents/LastUsage.kt
  src/main/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsService.kt
  src/test/kotlin/it/pagopa/ecommerce/users/UserTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/users/config/mongo/converters/MongoConverterTests.kt
  src/test/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsServiceTest.kt
Labels: size/small, minor, chart-minor

#8 [CHK-3288] feat: add business logic to retrieve user last method
  gradle/verification-metadata.xml
  src/main/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageController.kt
  src/main/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsService.kt
  src/test/kotlin/it/pagopa/ecommerce/users/UserTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/documents/UserStatisticsTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/services/UsersStatisticsServiceTest.kt
Labels: patch, chart-patch, size/small

#10 chore(logging): add basic information logging for last used data service
  src/main/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsService.kt
Labels: patch, chart-patch, size/small

#9 feat: api tests for CR pipeline
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  api-tests/localhost.postman_environment.json
  api-tests/user_stats_tests.postman_collection.json
Labels: size/large, skip-release

#11 feat: add warmup requests
  src/main/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageController.kt
  src/main/kotlin/it/pagopa/ecommerce/users/warmup/ControllersWarmup.kt
  src/main/kotlin/it/pagopa/ecommerce/users/warmup/annotations/WarmupFunction.kt
  src/main/kotlin/it/pagopa/ecommerce/users/warmup/exceptions/WarmUpException.kt
  src/main/kotlin/it/pagopa/ecommerce/users/warmup/utils/WarmupUtils.kt
Labels: size/small, minor, chart-minor

#13 chore(api): refactoring POST to PUT
  api-spec/v1/user-stats-api.yaml
  api-tests/user_stats_tests.postman_collection.json
  src/main/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageController.kt
  src/main/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsService.kt
  src/main/kotlin/it/pagopa/ecommerce/users/warmup/utils/WarmupUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/users/UserTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/users/controllers/v1/LastUsageControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsServiceTest.kt
Labels: size/small, minor, chart-minor

#14 feat: refactoring user statistics document
  src/main/kotlin/it/pagopa/ecommerce/users/documents/LastUsage.kt
  src/main/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsService.kt
  src/test/kotlin/it/pagopa/ecommerce/users/UserTestUtils.kt
  src/test/kotlin/it/pagopa/ecommerce/users/documents/UserStatisticsTest.kt
  src/test/kotlin/it/pagopa/ecommerce/users/services/UserStatisticsServiceTest.kt
Labels: size/small, minor, chart-minor

#15 fix: use ecommerce local for api tests
  .devops/azure-templates/api-tests.yml
  .devops/code-review-pipelines.yml
  api-tests/localhost.postman_environment.json
  api-tests/user_stats_tests.postman_collection.json
  build.gradle.kts
Labels: size/large, skip-release

#16 feat: enable deployment pipeline for PROD env
  .devops/deploy-pipelines.yml
Labels: major, chart-major
